// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/kontakt" | "/portal" | "/portal/cas" | "/portal/inventar" | "/portal/obvestila" | "/portal/opomniki" | "/portal/orodja" | "/portal/ponudbe" | "/portal/stranke" | "/portal/stranke/[id]" | "/reference" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]" | "/storitve" | "/vzdrzevalni-paketi"
type PageRoutes = never
type LayoutRoutes = "/" | "/portal"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/kontakt": {}
  "/portal": {}
  "/portal/cas": {}
  "/portal/inventar": {}
  "/portal/obvestila": {}
  "/portal/opomniki": {}
  "/portal/orodja": {}
  "/portal/ponudbe": {}
  "/portal/stranke": {}
  "/portal/stranke/[id]": { "id": string; }
  "/reference": {}
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
  "/storitve": {}
  "/vzdrzevalni-paketi": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/portal": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
